"use client"
import { useState } from 'react'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar"
import AuthLayout from '@/components/AuthLayout';
import Link from 'next/link'
import toast, { Toaster } from 'react-hot-toast';
import { Provider } from 'react-redux';
import { store, persistor } from '../store/store'
import { PersistGate } from "redux-persist/integration/react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
  const [auth, setAuth ] = useState(false)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor} >
        
          { 
            auth ?  <AuthLayout/> : <Navbar/>
          } 
          <Toaster/> 

            {children}
            
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
